# Based on https://conda.io/docs/user-guide/tasks/use-conda-with-travis-ci.html
language: c
matrix:
  include:
    - os: linux
      env:
        - PY=3.6
        - NUMPY=1.18.1
    - os: linux
      env:
        - PY=3.7
        - NUMPY=1.18.1
    - os: linux
      env:
        - PY=3.8
        - NUMPY=1.18.1
    - os: osx
      env:
        - PY=3.6
        - NUMPY=1.18.1
    - os: osx
      env:
        - PY=3.7
        - NUMPY=1.18.1
    - os: osx
      env:
        - PY=3.8
        - NUMPY=1.18.1
  allow_failures:
    - os: osx

install:
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then os=Linux; else os=MacOSX; fi
  - wget "https://repo.continuum.io/miniconda/Miniconda3-latest-${os}-x86_64.sh" -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - . $HOME/miniconda/etc/profile.d/conda.sh
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda create -q -n test-env python=$PY
  - conda activate test-env
  # Install kdb+
  - . .travis/getkdb.sh
  # Install requirements
  - conda install pytest pytest-cov coverage
  - if [ -n "${NUMPY}" ]; then conda install numpy-base==${NUMPY}; fi
  - pip install pytest-pyq
  - . .travis/build.sh


## install system packages
addons:
  apt: # apt-get for linux
    packages:
     - libc6:i386
     - gcc-multilib
script:
  - pyq --versions
  - pyq -mpytest --pyargs pyq
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then
      $QHOME/l32/q src/pyq/tests/test_embed.q;
    fi
