{% set name = "PyQ" %}

package:
  name: '{{ name|lower }}'
  version: '5.0.0'

source:
  path: .

build:
  number: 0
  script:
    - python -m pip install -f file://`pwd`/dist pyq
  detect_binary_files_with_prefix: false
  has_prefix_files:
    - q/pyq-config.q

requirements:
  build:
    - python
    - setuptools_scm
    - kdb
  run:
    - python
    - kdb

test:
  requires:
    - kdb
    - pytest
    - pytest-pyq
    - numpy
  commands:
    - echo .z.l | q
    # NB: For this to work, use conda build . --no-long-test-prefix
    - pyq --versions
    - pyq -mpytest --pyargs pyq

about:
  home: https://github.com/KxSystems/pyq
  license: Apache Software License
  license_family: APACHE
  license_file: 'LICENSE'
  summary: PyQ - Python for kdb+
  description: |
    PyQ - Python for kdb+
    =====================

    PyQ brings the [Python programming language](https://www.python.org/about)
    to the [kdb+ database](https://kx.com).  It allows developers to seamlessly integrate Python and q codes in one
    application.  This is achieved by bringing the Python and q interpreters in the same process so that codes written
    in either of the languages operate on the same data.  In PyQ, Python and q objects live in the same memory space
    and share the same data.
  doc_url: 'https://github.com/KxSystems/pyq/tree/master/docs'
  dev_url: 'https://github.com/KxSystems/pyq'

extra:
  recipe-maintainers: 'pyq@enlnt.com'
